# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-20 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('bestoflegs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeagueGrp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('captain', models.CharField(max_length=150)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Division')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='leaguegrp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.LeagueGrp'),
        ),
    ]