# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-23 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PandDDL', '0003_auto_20181123_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopFinishes',
            new_name='TopFinish',
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
    ]
