# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-25 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PandDDL', '0004_auto_20181123_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homescore', models.IntegerField()),
                ('awayscore', models.IntegerField()),
                ('date', models.DateField()),
                ('awayteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='PandDDL.Team')),
                ('hometeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='PandDDL.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homescore', models.IntegerField()),
                ('awayscore', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='leaguegrp',
            options={'verbose_name': 'League', 'verbose_name_plural': 'Leagues'},
        ),
        migrations.AlterModelOptions(
            name='topfinish',
            options={'verbose_name': 'Top Finish', 'verbose_name_plural': 'Top Finishes'},
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='awayplayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Fixture'),
        ),
        migrations.AddField(
            model_name='match',
            name='homeplayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='PandDDL.Player'),
        ),
    ]
