# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PandDDL', '0005_auto_20181125_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='fixtureentered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixture',
            name='fixtureverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
    ]
