# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PandDDL', '0006_auto_20181125_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='fixtureentered',
            new_name='resultentered',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='fixtureverified',
            new_name='resultverified',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
    ]
