# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-25 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PandDDL', '0007_auto_20181125_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='doubles_matches_ags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='doubles_matches_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='doubles_matches_lst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='doubles_matches_pld',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='doubles_matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='singles_matches_ags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='singles_matches_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='singles_matches_lst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='singles_matches_pld',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='singles_matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
    ]
