# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-25 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PandDDL', '0008_auto_20181125_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoublesMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homescore', models.IntegerField()),
                ('awayscore', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Match',
            new_name='SinglesMatch',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AddField(
            model_name='doublesmatch',
            name='awayplayer1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away1', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='doublesmatch',
            name='awayplayer2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away2', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='doublesmatch',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Fixture'),
        ),
        migrations.AddField(
            model_name='doublesmatch',
            name='homeplayer1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home1', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='doublesmatch',
            name='homeplayer2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home2', to='PandDDL.Player'),
        ),
    ]
