# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-30 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PandDDL', '0016_auto_20181130_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublesmatch',
            name='awaymaximums1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doublesmatch',
            name='awaymaximums2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doublesmatch',
            name='homemaximums1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doublesmatch',
            name='homemaximums2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='pointsdeduction',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
    ]
