# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-04 22:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PandDDL', '0022_auto_20181204_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupFixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homescore', models.IntegerField()),
                ('awayscore', models.IntegerField()),
                ('date', models.DateField()),
                ('resultentered', models.BooleanField(default=False)),
                ('resultverified', models.BooleanField(default=False)),
                ('walkover', models.BooleanField(default=False)),
                ('awayteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupaway', to='PandDDL.Team')),
                ('hometeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuphome', to='PandDDL.Team')),
                ('resultenteredby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CupRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.CupComp')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='division',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='pointsdeduction',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AddField(
            model_name='cupfixture',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.CupRound'),
        ),
    ]
