# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-29 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PandDDL', '0031_auto_20181229_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=1)),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('legs_for', models.IntegerField()),
                ('legs_against', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='away1finish1',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='away1finish2',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='away1finish3',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='away2finish1',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='away2finish2',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='away2finish3',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='awaymaximums1',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='awaymaximums2',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='home1finish1',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='home1finish2',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='home1finish3',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='home2finish1',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='home2finish2',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='home2finish3',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='homemaximums1',
        ),
        migrations.RemoveField(
            model_name='doublesmatch',
            name='homemaximums2',
        ),
        migrations.RemoveField(
            model_name='singlesmatch',
            name='awayfinish1',
        ),
        migrations.RemoveField(
            model_name='singlesmatch',
            name='awayfinish2',
        ),
        migrations.RemoveField(
            model_name='singlesmatch',
            name='awayfinish3',
        ),
        migrations.RemoveField(
            model_name='singlesmatch',
            name='awaymaximums',
        ),
        migrations.RemoveField(
            model_name='singlesmatch',
            name='homefinish1',
        ),
        migrations.RemoveField(
            model_name='singlesmatch',
            name='homefinish2',
        ),
        migrations.RemoveField(
            model_name='singlesmatch',
            name='homefinish3',
        ),
        migrations.RemoveField(
            model_name='singlesmatch',
            name='homemaximums',
        ),
        migrations.AlterField(
            model_name='cupfixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupaway', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='cupfixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuphome', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='pointsdeduction',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AddField(
            model_name='result',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Fixture'),
        ),
        migrations.AddField(
            model_name='result',
            name='opposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposition', to='PandDDL.Team'),
        ),
        migrations.AddField(
            model_name='result',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='PandDDL.Team'),
        ),
    ]
