# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-30 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PandDDL', '0032_auto_20181229_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoublesResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=1)),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('legs_for', models.IntegerField()),
                ('legs_against', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.DoublesMatch')),
            ],
        ),
        migrations.CreateModel(
            name='SinglesResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=1)),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('legs_for', models.IntegerField()),
                ('legs_against', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.SinglesMatch')),
            ],
        ),
        migrations.AlterField(
            model_name='cupfixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupaway', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='cupfixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuphome', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='pointsdeduction',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='result',
            name='opposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposition', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='result',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='PandDDL.Team'),
        ),
        migrations.AddField(
            model_name='singlesresult',
            name='opposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposition', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='singlesresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singlesplayer', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='doublesresult',
            name='opposition1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposition1', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='doublesresult',
            name='opposition2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposition2', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='doublesresult',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='doublesresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doublesplayer', to='PandDDL.Player'),
        ),
    ]
