# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-31 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PandDDL', '0033_auto_20181230_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='doubles_matches_ags',
        ),
        migrations.RemoveField(
            model_name='player',
            name='doubles_matches_for',
        ),
        migrations.RemoveField(
            model_name='player',
            name='doubles_matches_lst',
        ),
        migrations.RemoveField(
            model_name='player',
            name='doubles_matches_pld',
        ),
        migrations.RemoveField(
            model_name='player',
            name='doubles_matches_won',
        ),
        migrations.RemoveField(
            model_name='player',
            name='maximums',
        ),
        migrations.RemoveField(
            model_name='player',
            name='singles_matches_ags',
        ),
        migrations.RemoveField(
            model_name='player',
            name='singles_matches_for',
        ),
        migrations.RemoveField(
            model_name='player',
            name='singles_matches_lst',
        ),
        migrations.RemoveField(
            model_name='player',
            name='singles_matches_pld',
        ),
        migrations.RemoveField(
            model_name='player',
            name='singles_matches_won',
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches_ags',
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches_for',
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches_lst',
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches_pld',
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches_pts',
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches_won',
        ),
        migrations.AlterField(
            model_name='cupfixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupaway', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='cupfixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuphome', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='awayscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='homescore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='pointsdeduction',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='result',
            name='opposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposition', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='result',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='PandDDL.Team'),
        ),
    ]
