# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-04 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PandDDL', '0049_auto_20190124_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TriplesMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homescore', models.IntegerField(default=0)),
                ('awayscore', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Triples Match',
                'verbose_name_plural': 'Triples Matches',
            },
        ),
        migrations.CreateModel(
            name='TriplesResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=1)),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('legs_for', models.IntegerField()),
                ('legs_against', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.TriplesMatch')),
            ],
        ),
        migrations.AlterField(
            model_name='cupfixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupaway', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='cupfixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuphome', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='pointsdeduction',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='result',
            name='opposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposition', to='PandDDL.Team'),
        ),
        migrations.AlterField(
            model_name='result',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='PandDDL.Team'),
        ),
        migrations.AddField(
            model_name='triplesresult',
            name='opposition1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topposition1', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='triplesresult',
            name='opposition2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topposition2', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='triplesresult',
            name='opposition3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topposition3', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='triplesresult',
            name='partner1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner1', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='triplesresult',
            name='partner2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner2', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='triplesresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triplesplayer', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='triplesmatch',
            name='awayplayer1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taway1', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='triplesmatch',
            name='awayplayer2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taway2', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='triplesmatch',
            name='awayplayer3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taway3', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='triplesmatch',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Fixture'),
        ),
        migrations.AddField(
            model_name='triplesmatch',
            name='homeplayer1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thome1', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='triplesmatch',
            name='homeplayer2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thome2', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='triplesmatch',
            name='homeplayer3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thome3', to='PandDDL.Player'),
        ),
        migrations.AddField(
            model_name='topscore',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Fixture'),
        ),
        migrations.AddField(
            model_name='topscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PandDDL.Player'),
        ),
    ]
